#!/bin/bash
#  -*- Shell-Script -*-

DIST_CODENAME=$(lsb_release -c | cut -f2)

#http://archive.canonical.com/ubuntu/ maverick/partner amd64 Packages
add-apt-repository "deb http://archive.canonical.com/ ${DIST_CODENAME} partner"
apt-get update