(add-to-list 'auto-mode-alist '("\\.js$" . js-mode))
(add-to-list 'auto-mode-alist '("\\.json$" . js-mode))
(add-to-list 'auto-mode-alist '("\\.node$" . js-mode))
(add-to-list 'auto-mode-alist '("\\.host$" . js-mode))
(provide 'json-conf)
