#!/bin/bash
#-*- Shell-Script -*-


. "$SETUP_DATA_DIR/common-data"
. "$SETUP_DATA_DIR/common-functions"

set -e

BASHRC=/etc/bash.bashrc
BASHRC_BCK=/etc/bash.bashrc.donotdelete
if [ $STAGE = "setup-start" ]; then    
    cp ${BASHRC} ${BASHRC_BCK}
    cat >> ${CHROOT_PATH}/${BASHRC} <<EOF

if [ \$TERM = eterm-color ]; then
 function eterm-set-cwd {
 \$@
 echo -e "\033AnSiTc" ${CHROOT_PATH}/\$(pwd)
 }

 # set hostname, user, and cwd
 function eterm-reset {
 echo -e "\033AnSiTu" \$(whoami)
 echo -e "\033AnSiTc" ${CHROOT_PATH}/\$(pwd)
 echo -e "\033AnSiTh" \$(hostname)
 }

 for temp in cd pushd popd; do
 alias \$temp="eterm-set-cwd \$temp"
 done

 # set hostname, user, and cwd now
 eterm-reset
fi
EOF

elif [ $STAGE = "setup-stop" ]; then	
    if [[ -e ""${BASHRC_BCK}"" ]]; then
	mv ${BASHRC_BCK} ${BASHRC} 
    fi
fi
