#!/bin/bash
#  -*- Shell-Script -*-

#set -e

. /usr/local/sbin/echenv-utils.sh
. /usr/share/debconf/confmodule

# get user and group from debconf
db_get echenv/user
T_USER=${RET}
ENV_GROUP=echenv

SHORT_HOSTNAME=`hostname -s`
HOST_PROFILE=/home/${T_USER}/.${SHORT_HOSTNAME}_profile.sh

if [ -x "${HOST_PROFILE}" ] ; then
    . ${HOST_PROFILE}
else
    exit 1
fi

if [ -z "$DEV_HOME" ] ; then
    exit 1
fi

ROOT_DIR=/var/cache/echenv-emacs/
EMACS_PCK_DIR=${ROOT_DIR}/emacsdir
EMACS_DIR=${DEV_HOME}/emacsdir

mkdir -p ${EMACS_DIR}

cp -R ${EMACS_PCK_DIR}/* ${EMACS_DIR}
chown -R ${T_USER}.${ENV_GROUP} ${EMACS_DIR}
chmod -R 775 ${EMACS_DIR}

addtoprofiled /home/${T_USER} ${ROOT_DIR}/profiled/*.sh

rm -rf ${ROOT_DIR}